/**
 * Comprehensive enum of all error types in the application
 * Maps all error classes and their subtypes
 */

// Auth Error Types
export enum AuthErrorType {
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  SESSION_EXPIRED = "SESSION_EXPIRED",
}

// Database Error Types
export enum DatabaseErrorType {
  CONNECTION_FAILED = "CONNECTION_FAILED",
  QUERY_FAILED = "QUERY_FAILED",
  CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION",
  DUPLICATE_KEY = "DUPLICATE_KEY",
  NOT_FOUND = "NOT_FOUND",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  TIMEOUT = "TIMEOUT",
  INVALID_QUERY = "INVALID_QUERY",
  FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION",
}

// Validation Error Types
export enum ValidationErrorType {
  INVALID_TYPE = "INVALID_TYPE",
  TOO_SMALL = "TOO_SMALL",
  TOO_BIG = "TOO_BIG",
  INVALID_FORMAT = "INVALID_FORMAT",
  NOT_MULTIPLE_OF = "NOT_MULTIPLE_OF",
  UNRECOGNIZED_KEYS = "UNRECOGNIZED_KEYS",
  INVALID_UNION = "INVALID_UNION",
  INVALID_KEY = "INVALID_KEY",
  INVALID_ELEMENT = "INVALID_ELEMENT",
  INVALID_VALUE = "INVALID_VALUE",
  CUSTOM = "CUSTOM",
  FIELD_REQUIRED = "FIELD_REQUIRED",
  FIELD_LENGTH_INVALID = "FIELD_LENGTH_INVALID",
  DUPLICATE_VALUE = "DUPLICATE_VALUE",
}

// Document Error Types
export enum DocumentErrorType {
  GENERAL = "GENERAL",
  LOADING_ERROR = "LOADING_ERROR",
  RENDERING_ERROR = "RENDERING_ERROR",
  CORRUPTED = "CORRUPTED",
}

// Document Validation Error Types
export enum DocumentValidationErrorType {
  INVALID_FORMAT = "INVALID_FORMAT",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  FILE_TOO_SMALL = "FILE_TOO_SMALL",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_CONTENT = "INVALID_CONTENT",
}

// Storage Error Types
export enum StorageErrorType {
  UPLOAD_FAILED = "UPLOAD_FAILED",
  DOWNLOAD_FAILED = "DOWNLOAD_FAILED",
  DELETE_FAILED = "DELETE_FAILED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  INVALID_PATH = "INVALID_PATH",
  ACCESS_DENIED = "ACCESS_DENIED",
  NOT_FOUND = "NOT_FOUND",
}

// AI Error Types
export enum AIErrorType {
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  INVALID_REQUEST = "INVALID_REQUEST",
  PROCESSING_FAILED = "PROCESSING_FAILED",
  TIMEOUT = "TIMEOUT",
  INVALID_MODEL = "INVALID_MODEL",
  INSUFFICIENT_QUOTA = "INSUFFICIENT_QUOTA",
}

// Network Error Types
export enum NetworkErrorType {
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  CONNECTION_REFUSED = "CONNECTION_REFUSED",
  DNS_RESOLUTION_FAILED = "DNS_RESOLUTION_FAILED",
  SSL_CERTIFICATE_ERROR = "SSL_CERTIFICATE_ERROR",
  BAD_GATEWAY = "BAD_GATEWAY",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  REQUEST_FAILED = "REQUEST_FAILED",
}

// General Error Types
export enum GeneralErrorType {
  UNKNOWN = "UNKNOWN",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  DEPRECATED = "DEPRECATED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

/**
 * Union type of all error types
 */
export type AllErrorTypes = 
  | AuthErrorType
  | DatabaseErrorType
  | ValidationErrorType
  | DocumentErrorType
  | DocumentValidationErrorType
  | StorageErrorType
  | AIErrorType
  | NetworkErrorType
  | GeneralErrorType;

/**
 * Error class mapping for runtime error type checking
 */
export const ERROR_CLASS_MAP = {
  [AuthErrorType.AUTHENTICATION_REQUIRED]: "AuthError",
  [DatabaseErrorType.CONNECTION_FAILED]: "DatabaseError",
  [ValidationErrorType.INVALID_TYPE]: "ValidationError",
  [DocumentErrorType.LOADING_ERROR]: "DocumentError",
  [DocumentValidationErrorType.INVALID_FORMAT]: "DocumentValidationError",
  [StorageErrorType.UPLOAD_FAILED]: "StorageError",
  [AIErrorType.RATE_LIMIT_EXCEEDED]: "AIError",
  [NetworkErrorType.CONNECTION_TIMEOUT]: "NetworkError",
  [GeneralErrorType.UNKNOWN]: "GeneralError",
} as const;